EvanNotFound/hexo-theme-redefine

_config.yml
layout/_partials/comments/twikoo.ejs

Add Comment system version control, so user can change comment system version directly from _config.yml. As a test, it only add twikoo at this point.
This was inspired from hexo-theme-fluid
=========================
This may or may not be the best practices, but I do see some of the theme has similar function. 
Example: The _config.yml use twikoo 1.6.8 by default, I can change it to 1.6.9 directly without putting theme to theme/redefine/layout. And here are the test preview:

Add Comment Version Control

---

layout/_partials/head.ejs

head 裡面的 `og:url` 沒有正常的接合，少了一個 `/`，就像下面這樣
```html
<meta property="og:url" content="http://redefine.ohevan.comindex.html">
```
把原本的 `config.url + page.path` 換成 `full_url_for(page.path)` 就可以修好了
https://hexo.io/docs/helpers#full-url-for

head: fix `og:url`

---

source/js/layouts/navbarShrink.js

手機版的 navbar 的選單開啟按鈕有的時候會無法運作
前往 https://redefine.ohevan.com/ （需要是有選單展開按鈕的狹窄手機頁面）
不要進行任何的捲動，確保這是第一個到達的頁面，因為這會受到 `pjax` 的影響
此時會發現 navbar 的選單開啟按鈕 無法正常運作
頁面剛載入完成時
下面的兩個地方都會執行 `navbarShrink.init()` 一次
https://github.com/EvanNotFound/hexo-theme-redefine/blob/main/source/js/layouts/navbarShrink.js#L44
https://github.com/EvanNotFound/hexo-theme-redefine/blob/main/source/js/main.js#L46
在執行了兩個 `navbarShrink.init()` 的狀態下 選單開啟按鈕會 無法正常運作
原因在於這個地方會被執行兩次
https://github.com/EvanNotFound/hexo-theme-redefine/blob/main/source/js/layouts/navbarShrink.js#L38
```javascript
v.addEventListener('click', () => {
document.body.classList.toggle('navbar-drawer-show');
});
```
那個地方被執行兩次的意思就是 選單按鈕會有兩個相同的 `EventListener` 
做的事情是 `toggle('navbar-drawer-show')`
`toggle` 兩次的意思等於沒有 `toggle`
所以選單不會正常打開
然後如果這個時候進行了捲動的動作 …

navbar: fix navbar-drawer not open bug

---

source/js/utils.js

當 `global.scroll_progress.bar` `global.scroll_progress.percentage` 的設定都是 `false` 時 
`navbar.auto_hide` 設定成 `true` 仍不會有 auto_hide 的效果
auto_hide 的功能是由 `updateScrollStyle` 這個 function 來處理的
https://github.com/EvanNotFound/hexo-theme-redefine/blob/91fa018a194e69a198ef9861e8c811452708b560/source/js/utils.js#L45
https://github.com/EvanNotFound/hexo-theme-redefine/commit/afbb3e966f5d2b55dd16ee7797a4dab8ea532c2f
所以來看看 `updateScrollStyle` 什麼時候會被呼叫到
可以從下面這段 code 發現
`this.isHasScrollPercent || this.isHasScrollProgressBar` 成立的情況下才會執行到 `updateScrollStyle` 
然後才會執行到 auto_hide 的部分
所以 `this.isHasScrollPercent || this.isHasScrollProgressBar` 為 `false` 的時候 auto_hide 就不會正常運作
https://github.com/EvanNotFound/hexo-theme-redefine/blob/main/source/js/utils.js#L57-L59
```javascript
registerWindowScroll() { …
```

navbar: fix auto_hide bug

---

layout/_partials/navbar.ejs
source/js/layouts/navbarShrink.js

來到 https://redefine.ohevan.com/ 的手機版頁面
打開 navbar 選單
此時若點選在 `LINKS` 底下的 submenu 裡的 `SHOWCASE`
會正常跳轉到 https://redefine.ohevan.com/showcase
只不過跳轉過去的時候選單還是開著的
預期應該要和點選 navbar 裡的 `HOME` 時一樣關閉選單然後跳去 home 
在 submenu 裡的東西被點的時候把選單關起來

navbar: close drawer-navbar after click on submenu

---

layout/_partials/head.ejs

`apple-touch-icon` 的 tag 重複出現
而第一次出現的 `apple-touch-icon` 的 `href` 會是 404 not found
所以把第一次出現的那個移除
https://github.com/EvanNotFound/hexo-theme-redefine/blob/main/layout/_partials/head.ejs#L7
https://github.com/EvanNotFound/hexo-theme-redefine/blob/main/layout/_partials/head.ejs#L30

head: remove repetitive apple-touch-icon tag

---

layout/_partials/head.ejs

使用 Hexo 的 open-graph helper 的時候
他就會自動幫網站加上 `<meta name="description" >` 了
所以 `open_graph` 開著的時候會出現重複的 description tag
判斷 `open_graph` 開著的時候就不要再額外放 description tag ，避免重複

head: remove repetitive description tag

---

source/js/layouts/navbarShrink.js

類似 #121
手機版頁面中打開 navbar 選單
點選 logo-title 時會回到首頁
但跳轉到首頁時選單還是開著的
預期應該要和點選 navbar 裡的 `HOME` 時一樣關閉選單然後跳去 home

navbar: close drawer after click on logo-title

---

source/assets/fonts.css

使用 CDN 時，用 relative path 才能夠取到正確的資源。
比如使用 /fonts/open-sans-v34-latin-regular.woff2 以及 jsdelivr 時 會變成 https://cdn.jsdelivr.net/fonts/open-sans-v34-latin-regular.woff2 
但 https://cdn.jsdelivr.net/npm/hexo-theme-redefine@2.1.2/fonts/open-sans-v34-latin-regular.woff2 才是我們要的

fonts: use relative path

---

_config.yml
layout/_partials/comments/comment.ejs
layout/_partials/comments/giscus.ejs
source/js/tools/lightDarkSwitch.js

#163 
到 https://giscus.app/ 頁面中的 Configuration 部分依照指示將資料填好。
填好之後下方的 Enable giscus 部分會出現類似以下的內容。
```html
<script src="https://giscus.app/client.js"
data-repo="ching367436/ching367436.github.io"
data-repo-id="R_kgDOJNMXOw"
data-category="Announcements"
data-category-id="DIC_kwDOJNMXO84CVdDe"
data-mapping="title"
data-strict="0"
data-reactions-enabled="1"
data-emit-metadata="0"
data-input-position="bottom"
data-theme="preferred_color_scheme"
data-lang="en"
crossorigin="anonymous"
async>
</script>
```
將上面生成的各項對應資料填入 `_config.redefine.yml`，如下面這樣。
`data-theme`、`crossorigin` 不用填。
特別注意 `mapping` 的部分在 `pjax` 開啟的情況下不要選用 `og:title`，會出問題。
```yml
comment:
system: giscus
config:
giscus:
repo: Ching367436/ching367436.github.io # Github repository name
repo_id: R_kgDOJNMXOw # Github repository id …
```

giscus: add support

---

layout/_widgets/friends-link.ejs
source/css/layout/_partials/page-template.styl

New friend link page.
Preview:
Features:
- Categories
- Site Thumbnail
The users should change their links.yml to something like this:
```yml
- links_category: Elites
has_thumbnail: true
list: 
- name: EvanNotFound's Blog
link: https://ohevan.com
description: 用香港记者的速度更新文章
avatar: https://evan.beee.top/avatar.png
thumbnail: https://img1.imgtp.com/2023/06/19/Jegvz84P.png
- name: 安仔の午睡床
link: https://anzai.sleepingbed.top/
description: 啊对对对，开摆就完了呗
avatar: https://cdn.tianli0.top/gh/anzai249/anzai249.github.io@main/images/Avatar.jpg
thumbnail: https://img1.imgtp.com/2023/06/19/oarRFKkz.png
- links_category: Normal
has_thumbnail: false
list: 
- name: Example Site
link: https://example.com
description: Example Site Description
avatar: https://www.youtube.com/watch?v=dQw4w9WgXcQ
- name: Example …
```

New friend link page

---

_config.yml
layout/_partials/home-banner.ejs
source/css/layout/_partials/home-banner.styl

Preview:
You should edit your config to something like this:
```yml
social_links:
enable: false
links:
github:  # your GitHub URL
instagram: # your Instagram URL
zhihu:  # your ZhiHu URL
twitter:  # your twitter URL
email:  # your email
qrs:
weixin: # your Wechat QRcode image URL
```
You can paste any URL of images here, and if you don't want to use this feature you can just leave it blank.

New social link supports QRcode drawer

---

source/css/layout/_partials/navbar.styl

- 修复了移动端菜单过长无法点击的问题
- Fixed the problem of the mobile menu being too long to click
**before**
https://github.com/EvanNotFound/hexo-theme-redefine/assets/59012240/4c255991-a4a7-41c9-a6ab-3ca079df6289
**after**
https://github.com/EvanNotFound/hexo-theme-redefine/assets/59012240/e91f4f2f-0202-498b-946b-dc88caf369f7

navbar: Fix menu overflow issue

---

source/css/layout/article-content.styl

手机端tag显示超宽，所有tag都显示在一行，修正为自动换行，可以展示文章所有tag。

fix issue #258

---

source/css/layout/_partials/home-banner.styl

- Adjust the size of the QR code image
- Make `social-qr-container` and `social-contacts` right aligned.
before:

home-banner: Adjust QR code image

---

_config.yml
layout/_partials/footer.ejs

Update the counter API URL in _config.yml and footer.ejs from 'https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js' to 'https://vercount.one/js'. This change enables accurate website visit count.

hotfix: Update website counter API URL

---

_config.yml
languages/en.yml
languages/ja.yml
languages/zh-CN.yml
languages/zh-TW.yml
layout/_partials/footer.ejs
layout/_partials/head.ejs
layout/_partials/home-background.ejs
layout/_partials/home-banner.ejs
layout/_partials/navbar.ejs
layout/_partials/scripts.ejs
layout/_widgets/archive-list.ejs
package-lock.json
package.json
scripts/events/welcome.js
source/assets/build/styles.css
source/css/common/markdown.styl
source/css/common/variables.styl
source/css/layout/_partials/archive-list.styl
source/css/layout/_partials/navbar.styl
source/css/layout/_partials/page-template.styl
source/js/main.js
tailwind.config.js

#335: Site generation bug fixed.
#323: Image caption alignment corrected to center.
#322: Removed whitespace below the footer after preloader is disabled.
#321: Fixed the injector's location from head_end to body.
#317: Background images on non-home pages are now properly displayed.
#331: Mobile view now includes a sidebar menu for easier navigation in the blog.
#330: Default dark mode option added for user preference.
#324: Adjusted column spacing in categories and modified link selection to prevent accidental navigation.
#316: Social links and dropdown arrow positions have been updated for better accessibility.
#272: Enhanced title spacing customization options.
#242: Implemented support for displaying total word count on pages.

Bump version to 2.6.1

---

_config.yml
source/css/layout/_modules/aplayer.styl
source/js/plugins/aplayer.js

- The properties in the aplayer.styl file cause the lyrics button in Applayer to be invalid. (gray, unable to be triggered)
- The lyrics cannot be displayed after the lrc file is imported into the link.
- Applayer lyrics button now triggers properly.
**Before:** The button was gray and could not be triggered. 
**Now:**
https://github.com/EvanNotFound/hexo-theme-redefine/assets/136422874/e023eee5-dbbc-4c53-afa5-3934b2c8bbdb
- The lrc file can be added correctly and the lyrics can be displayed, and the lyrics can be hidden by default when the page is loaded.

Fix aplayer bug

---

_config.yml

- Remove 'wasd' as the default value for recaptchaV3Key in Waline config
- Enhance security by not exposing a potentially sensitive key in config

refactor: Remove default value for Waline recaptchaV3Key

---

.github/workflows/preview-deployment.yml
.github/workflows/production-deployment.yml

- Update Vercel deployment action from v1.1.0 to v1.2.0
- Ensure latest version of GitHub Action is used for deployment

ci: upgrade Vercel deployment GitHub Action to v1.2.0

---

layout/pages/shuoshuo/essays.ejs

I fixed the timezone problem. The issue address is [#515](https://github.com/EvanNotFound/hexo-theme-redefine/issues/515).

fix: correct date formatting in essays.ejs to ensure proper timezone handling #515 #465
